apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  BROKER_HOSTNAME: "{{ .Values.rabbitmq.hostname }}"
  BROKER_PORT: "{{ .Values.rabbitmq.port }}"
  BROKER_USERNAME: "{{ .Values.rabbitmq.username }}"
  BROKER_PASSWORD: "{{ .Values.rabbitmq.password }}"
  BROKER_VIRTUALHOST: "{{ .Values.rabbitmq.virtualhost }}"